### ISSUE TITLE
Easy New File free in italian

### ISSUE THREAD

**Issue by pfascia** [SkStore/Easy-New-File#1]
Hi, I downloaded your app, free version, and find it useful, I do not have problem with it in english, but just for uniformity I would like to have it in italian, at least when right clicking, "Nuovo File" instead of New file Here. Is this a change I can do by myself? Like to modify a string? I am willing to translate it fully in italian, free, if You want. This is for both the apps, free and buyable.
Let me know about it.
Regards
Paolo

**Comment by liufsd** [comment]
wow ~
thanks.
Please connect me.  liupwade@gmail.com
I will send your  strings file later.
Thanks again.
