### ISSUE TITLE
Override with Mega.nz Finder extension

### ISSUE THREAD

**Issue by yasithab** [SkStore/Easy-New-File#10]
Easy-New-File Finder extension overrides MegaSync client finder overlay (sync) icon. Could you please check on this? I always need to disable and reenable Easy-New-File finder extension in order to make MegaSync overlay icon work.

<img width="1379" alt="Screenshot 2019-11-17 at 09 32 04" src="https://user-images.githubusercontent.com/9078175/69002880-9e22be00-091d-11ea-90ee-efe5bc4a4895.png">
<img width="1378" alt="Screenshot 2019-11-17 at 09 32 20" src="https://user-images.githubusercontent.com/9078175/69002881-a11dae80-091d-11ea-8ee2-a71ea32deda6.png">

**Comment by liufsd** [comment]
sorry . like this issue: https://github.com/SkStore/Easy-New-File/issues/12

**Comment by yasithab** [comment]
> sorry . like this issue: #12

Did you fix this?
