### ISSUE TITLE
Macosx Mojave freezes when creating a new file

### ISSUE THREAD

**Issue by pfascia** [SkStore/Easy-New-File#13]
Hi, after installing it and enablig it in system preference, if I try to open a new document, it freezes completely my imac, after ten second it asks for the name and then freezes for a minute before creating it

**Comment by liufsd** [comment]
Please upgrade to v5.0 .

**Comment by pfascia** [comment]
Already done before opening issue, 5.0 give same results as older versions

**Comment by liufsd** [comment]
Please try to relaunch your Finder.

**Comment by pfascia** [comment]
Same thing

**Comment by liufsd** [comment]
![image](https://user-images.githubusercontent.com/1910405/98467247-3987ff80-220f-11eb-8b3e-2ec3495f2037.png)

**Comment by pfascia** [comment]
NO,actually.. thanks for your time
