### ISSUE TITLE
Bad Russian translation (App Store version)

### ISSUE THREAD

**Issue by JohnDoe-404** [SkStore/Easy-New-File#21]
App Store version.

Hello. Translation into Russian is bad. I'm ready to help. Submit localization files.

**Comment by liufsd** [comment]
[strings.zip](https://github.com/SkStore/Easy-New-File/files/11854200/strings.zip)
Wow !!! 
Thanks.!.!

**Comment by JohnDoe-404** [comment]
@liufsd Did. You can update.
[strings_new.zip](https://github.com/SkStore/Easy-New-File/files/11893152/strings_new.zip)

**Comment by liufsd** [comment]
okk!
![image](https://github.com/SkStore/Easy-New-File/assets/1910405/d0e16a2c-f521-44cf-b130-848b75fd2700)

**Comment by JohnDoe-404** [comment]
@liufsd Updated. Thank you!
<img width="815" alt="image" src="https://github.com/SkStore/Easy-New-File/assets/52704675/4938905d-531b-4be6-bee4-565e5c2e553d">

**Comment by liufsd** [comment]
Thanks.
