### ISSUE TITLE
High memory usage (160 MB RAM)

### ISSUE THREAD

**Issue by uschmelzer** [SkStore/Easy-New-File#3]
If you can find the time, please explain the relatively high memory usage of "Easy New File". On my mac, it uses 160 MB RAM. I would expect it to use much less, say 6 MB like the dropbox finder extension.

## Details
- On my mac with OS High Sierra (10.13.2) it spawns two processes, which use around 80 MB RAM, each. Resulting in 160 MB RAM usage, total. For details see the attached screenshots.
- I'm using Easy New File from the Appstore, the paid version. 

![usage](https://user-images.githubusercontent.com/612622/35188022-6f7e6f8c-fe2e-11e7-83fa-8e44dd12ab6b.png)

![os](https://user-images.githubusercontent.com/612622/35188023-715b9924-fe2e-11e7-859d-1499f5977a3e.png)

Thank you for your time

**Comment by liufsd** [comment]
oh, no, sorry about that . which version do you download ?
![image](https://user-images.githubusercontent.com/1910405/35189948-13c7854e-fe91-11e7-95ca-77709f8023ff.png)
![image](https://user-images.githubusercontent.com/1910405/35189950-2c0bf806-fe91-11e7-85e1-f14043e45d7e.png)

**Comment by uschmelzer** [comment]
Version 3.1 (37) from the AppStore

**Comment by uschmelzer** [comment]
Maybe the memory usage of Easy New File is in relation to  the memory usage of the finder? E.g. now it is 900 MB for Easy New File vs. 100 MB for the finder. See screenshot.

![memory2](https://user-images.githubusercontent.com/612622/35197273-446bbb2e-fedd-11e7-9f98-e977ffdc7815.png)

**Comment by liufsd** [comment]
HI!~
You can try to kill this process , and then reopen it, watch the new memory.
Sorry, i have no idea about this at this time.
I will test it  and wish to help you to fix this.
Thanks.

**Comment by uschmelzer** [comment]
Thank you.

**Comment by liufsd** [comment]
By the way, do you have add the 'custom template' ?

![image](https://user-images.githubusercontent.com/1910405/35201465-b0c4c486-ff56-11e7-9365-f3dee0489074.png)

**Comment by uschmelzer** [comment]
> By the way, do you have add the 'custom template' 
> 
No. I create only one file. 

My context menu has no "Easy new file" entry (and I don't need it).
Screenshot 1:




Im using it from the menu bar, to only create one file named "Aufgabe.md".
Screenshot 2:

**Comment by uschmelzer** [comment]
Correction:
This is how my context menu looks like:
![screenshot3](https://user-images.githubusercontent.com/612622/35202184-6072b2c0-ff21-11e7-8b56-7c0bf5f4092c.png)

**Comment by liufsd** [comment]
ok.

**Comment by liufsd** [comment]
Hello. 
Please update to v4.0.
Thanks.

**Comment by uschmelzer** [comment]
thanks

**Comment by naveenisnoob** [comment]
Hi. Can I deselect templates under preference settings. I generally use NOTE PAD, WORD and EXCEL
![post](https://user-images.githubusercontent.com/40118164/41191549-0417fd4a-6c0f-11e8-9210-c9f56bb9e0db.png)

**Comment by liufsd** [comment]
Yes. Next version.

**Comment by naveenisnoob** [comment]
When I create a new text file and save the same, Right click and reopening the same file under dock is not getting displayed. Word and Excel have no such issues
![notepad](https://user-images.githubusercontent.com/40118164/41723781-97777628-7589-11e8-8f2a-ada8ffdc2ae8.png)

**Comment by liufsd** [comment]
Ok. Sorry . you mean that you open my file , but the Notepad does not show dock icon ???  Maybe you can try to open text file by System TextEdit.
Thank you.

**Comment by naveenisnoob** [comment]
When I try to open the text file created by using NEW FILE HERE under dock,
file is not visible. Notepad is working in dock and icon is also getting
displayed

**Comment by liufsd** [comment]
sorry please record a video.
