### ISSUE TITLE
After reinstall the whole system and install Easy New File, I can not see the context menu.

### ISSUE THREAD

**Issue by duskalbatross** [SkStore/Easy-New-File#6]
![image](https://user-images.githubusercontent.com/12107982/39996328-b71adba0-57b1-11e8-9e92-c490ffb0e384.png)
![image](https://user-images.githubusercontent.com/12107982/39996339-bc9ee4c2-57b1-11e8-9d37-aba8ff0c014c.png)
I tried relaunch finder and  System Preferences->Extensions ->enable Easy New File, but can not resolve the issue.
Thanks.

**Comment by duskalbatross** [comment]
![image](https://user-images.githubusercontent.com/12107982/39996436-0c3f31da-57b2-11e8-86d5-92cb73b48216.png)
The submenu has no content.

**Comment by liufsd** [comment]
sorry  sorry sorry.
It will fix at tomorrow morning . the v3.9.

**Comment by liufsd** [comment]
I’m waiting for the apple review at this night.
Sorry!

**Comment by duskalbatross** [comment]
That's OK! Take your time！加油↖(^ω^)↗👍🏻

    
        
            
                
                    
                        
                    
                    
                        
                            李颖晖
                            
                            
                                
                                    邮箱：duskalbatross@gmail.com
                                
                        
                    
                
            
        
    
签名由 网易邮箱大师 定制
On 05/14/2018 21:21, liupeng wrote: I’m waiting for the apple review at this night.
Sorry!

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/SkStore/Easy-New-File","title":"SkStore/Easy-New-File","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/SkStore/Easy-New-File"}},"updates":{"snippets":[{"icon":"PERSON","message":"@liufsd in #6: I’m waiting for the apple review at this night.\r\nSorry!  "}],"action":{"name":"View Issue","url":"https://github.com/SkStore/Easy-New-File/issues/6#issuecomment-388814216"}}}
{"@type":"MessageCard","@context":"http://schema.org/extensions","hideOriginalBody":"false","originator":"37567f93-e2a7-4e2a-ad37-a9160fc62647","title":"Re: [SkStore/Easy-New-File] After reinstall the whole system and install Easy New File, I can not see the context menu. (#6)","sections":[{"text":"","activityTitle":"**liupeng**","activityImage":"https://avatars2.githubusercontent.com/u/1910405?s=160\u0026v=4","activitySubtitle":"@liufsd","facts":[]}],"potentialAction":[{"name":"Add a comment","@type":"ActionCard","inputs":[{"isMultiLine":true,"@type":"TextInput","id":"IssueComment","isRequired":false}],"actions":[{"name":"Comment","@type":"HttpPOST","target":"https://api.github.com","body":"{\"commandName\":\"IssueComment\",\"repositoryFullName\":\"SkStore/Easy-New-File\",\"issueId\":6,\"IssueComment\":\"{{IssueComment.value}}\"}"}]},{"name":"Close issue","@type":"HttpPOST","target":"https://api.github.com","body":"{\"commandName\":\"IssueClose\",\"repositoryFullName\":\"SkStore/Easy-New-File\",\"issueId\":6}"},{"targets":[{"os":"default","uri":"https://github.com/SkStore/Easy-New-File/issues/6#issuecomment-388814216"}],"@type":"OpenUri","name":"View on GitHub"},{"name":"Unsubscribe","@type":"HttpPOST","target":"https://api.github.com","body":"{\"commandName\":\"MuteNotification\",\"threadId\":334932112}"}],"themeColor":"26292E"}

**Comment by liufsd** [comment]
hi，please update to v3.9
thanks

**Comment by duskalbatross** [comment]
早上更新了3.9的版本，可是问题还是没有解决😂

    
        
            
                
                    
                        
                    
                    
                        
                            李颖晖
                            
                            
                                
                                    邮箱：duskalbatross@gmail.com
                                
                        
                    
                
            
        
    
签名由 网易邮箱大师 定制
On 05/15/2018 07:27, liupeng wrote: hi，please update to v3.9
thanks

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/SkStore/Easy-New-File","title":"SkStore/Easy-New-File","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/SkStore/Easy-New-File"}},"updates":{"snippets":[{"icon":"PERSON","message":"@liufsd in #6: hi，please update to v3.9\r\nthanks"}],"action":{"name":"View Issue","url":"https://github.com/SkStore/Easy-New-File/issues/6#issuecomment-388994261"}}}
{"@type":"MessageCard","@context":"http://schema.org/extensions","hideOriginalBody":"false","originator":"37567f93-e2a7-4e2a-ad37-a9160fc62647","title":"Re: [SkStore/Easy-New-File] After reinstall the whole system and install Easy New File, I can not see the context menu. (#6)","sections":[{"text":"","activityTitle":"**liupeng**","activityImage":"https://avatars2.githubusercontent.com/u/1910405?s=160\u0026v=4","activitySubtitle":"@liufsd","facts":[]}],"potentialAction":[{"name":"Add a comment","@type":"ActionCard","inputs":[{"isMultiLine":true,"@type":"TextInput","id":"IssueComment","isRequired":false}],"actions":[{"name":"Comment","@type":"HttpPOST","target":"https://api.github.com","body":"{\"commandName\":\"IssueComment\",\"repositoryFullName\":\"SkStore/Easy-New-File\",\"issueId\":6,\"IssueComment\":\"{{IssueComment.value}}\"}"}]},{"name":"Close issue","@type":"HttpPOST","target":"https://api.github.com","body":"{\"commandName\":\"IssueClose\",\"repositoryFullName\":\"SkStore/Easy-New-File\",\"issueId\":6}"},{"targets":[{"os":"default","uri":"https://github.com/SkStore/Easy-New-File/issues/6#issuecomment-388994261"}],"@type":"OpenUri","name":"View on GitHub"},{"name":"Unsubscribe","@type":"HttpPOST","target":"https://api.github.com","body":"{\"commandName\":\"MuteNotification\",\"threadId\":334932112}"}],"themeColor":"26292E"}

**Comment by liufsd** [comment]
啊？ 你把设置都打开的情况下还不可以么？？？

**Comment by liufsd** [comment]
![image](https://user-images.githubusercontent.com/1910405/40038043-c2f6ab02-5842-11e8-9cab-da90e275eab7.png)
![image](https://user-images.githubusercontent.com/1910405/40038048-c7555400-5842-11e8-8ec0-ec73c98df1b4.png)

**Comment by duskalbatross** [comment]
是的，所有设置都打开了，又卸载重装了好几次，还是不行，菜单就一层，点开后没东西，下面是截图：
![image](https://user-images.githubusercontent.com/12107982/40039411-eb5ea922-5848-11e8-8000-c2268f46e575.png)
![image](https://user-images.githubusercontent.com/12107982/40039432-034e0910-5849-11e8-9382-4ddfd1734999.png)
![image](https://user-images.githubusercontent.com/12107982/40039439-0b3f4b0c-5849-11e8-872e-3393f9a6fa9a.png)

**Comment by liufsd** [comment]
尝试把几个选项都关了，在打开，然后尝试重启下Finder。 可能是系统的bug.

**Comment by duskalbatross** [comment]
显示出来了😂这也太诡异了，解决的流程是这样的：
1. 去掉扩展的勾选
2. 把所有偏好设置里面所有的选择全都去掉
3. 然后重启系统
4. 重启后，把扩展里勾上
5. 然后在偏好设置里面把一项一项都勾上
6. 然后就出来了。
貌似这个和扩展和偏好设置的顺序有关系，我再试几次。

**Comment by liufsd** [comment]
神奇+1。。。

**Comment by liufsd** [comment]
您好。
昨晚发布4.0版本，默认是关闭了外置硬盘的支持。您可以更新一下试试。

**Comment by jasonzhu-x** [comment]
what @duskalbatross said works, but I skipped step3.

**Comment by liufsd** [comment]
@ZhuXiaomin 👍
